# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript&WT.mc_id=sinediedsmoke-github-yolasors

strategy:
  matrix:
    linux-node10:
      imageName: 'ubuntu-latest'
      nodeVersion: '10.x'
    linux-node-latest:
      imageName: 'ubuntu-latest'
      nodeVersion: '12.x'
    mac-node10:
      imageName: 'macos-latest'
      nodeVersion: '10.x'
    mac-node-latest:
      imageName: 'macos-latest'
      nodeVersion: '12.x'
    windows-node10:
      imageName: 'windows-latest'
      nodeVersion: '10.x'
    windows-node-latest:
      imageName: 'windows-latest'
      nodeVersion: '12.x'

pool:
  vmImage: $(imageName)

trigger:
- master

schedules:
- cron: "0 12 * * 1"
  always: true
  branches:
    include:
    - master
  displayName: Weekly monday build

steps:
  # Needed to avoid issues with Prettier & Jest snapshots
- script: git config --global core.autocrlf false
  displayName: Disable git automatic line ending conversion

- checkout: self
  fetchDepth: 1

- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: Install Node.js

- script: npm install
  displayName: Install dependencies

- script: npm test
  displayName: Run unit tests
